/**
 * AstroMoon — GeoJSON Parser & Projector
 * Handles parsing GeoJSON files and projecting lon/lat to canvas coordinates.
 * Supports multi-layer accumulation with layer index tracking.
 */

/**
 * Parse a GeoJSON string into normalized features.
 */
function parse(text) {
  const data = JSON.parse(text);
  return _parseData(data);
}

/**
 * Parse an already-parsed GeoJSON object (no JSON.parse needed).
 */
function parseObject(data) {
  return _parseData(data);
}

function _parseData(data) {
  if (data.type !== 'FeatureCollection') {
    throw new Error('Expected a FeatureCollection');
  }

  const features = [];
  let minLon = Infinity, maxLon = -Infinity;
  let minLat = Infinity, maxLat = -Infinity;

  for (const feature of data.features) {
    const geom = feature.geometry;
    if (!geom) continue;

    const normalized = normalizeGeometry(geom);
    if (!normalized) continue;

    for (const ring of normalized.coords) {
      for (const [lon, lat] of ring) {
        if (lon < minLon) minLon = lon;
        if (lon > maxLon) maxLon = lon;
        if (lat < minLat) minLat = lat;
        if (lat > maxLat) maxLat = lat;
      }
    }

    features.push({
      type: normalized.type,
      coords: normalized.coords,
      properties: feature.properties || {},
      layerIndex: 0
    });
  }

  return {
    features,
    bounds: { minLon, maxLon, minLat, maxLat },
    name: data.name || 'unnamed'
  };
}

function normalizeGeometry(geom) {
  switch (geom.type) {
    case 'Point':
      return { type: 'point', coords: [[[geom.coordinates[0], geom.coordinates[1]]]] };

    case 'MultiPoint':
      return { type: 'point', coords: [geom.coordinates.map(c => [c[0], c[1]])] };

    case 'LineString':
      return { type: 'line', coords: [geom.coordinates.map(c => [c[0], c[1]])] };

    case 'MultiLineString':
      return {
        type: 'line',
        coords: geom.coordinates.map(line => line.map(c => [c[0], c[1]]))
      };

    case 'Polygon':
      return {
        type: 'polygon',
        coords: geom.coordinates.map(ring => ring.map(c => [c[0], c[1]]))
      };

    case 'MultiPolygon':
      return {
        type: 'polygon',
        coords: geom.coordinates.flat().map(ring => ring.map(c => [c[0], c[1]]))
      };

    default:
      console.warn('Unsupported geometry type:', geom.type);
      return null;
  }
}

/**
 * Project a single point (Lon/Lat) onto normalized [0, 1] orthographic coords.
 */
function projectPoint(lon, lat) {
  if (!window.appMoonState) return null;
  const lat0 = (window.appMoonState.librationLat || 0) * Math.PI / 180;
  const lon0 = (window.appMoonState.librationLon || 0) * Math.PI / 180;

  const rLon = lon * Math.PI / 180;
  const rLat = lat * Math.PI / 180;

  const cosC = Math.sin(lat0) * Math.sin(rLat) + Math.cos(lat0) * Math.cos(rLat) * Math.cos(rLon - lon0);
  if (cosC < 0) return null;

  const x = Math.cos(rLat) * Math.sin(rLon - lon0);
  const y = Math.cos(lat0) * Math.sin(rLat) - Math.sin(lat0) * Math.cos(rLat) * Math.cos(rLon - lon0);

  return [(x * 0.5) + 0.5, (-y * 0.5) + 0.5];
}

function project(features) {
  return features.map(f => {
    const projected = {
      type: f.type,
      properties: f.properties,
      layerIndex: f.layerIndex,
      coords: f.coords,
      projectedCoords: f.coords.map(ring =>
        ring.map(([lon, lat]) => projectPoint(lon, lat))
      )
    };
    // Preserve LOD data if present (generated by Worker/GeoJSONLod)
    if (f.lodCoords) projected.lodCoords = f.lodCoords;
    return projected;
  });
}

/**
 * Inverse Orthographic Projection with libration support.
 */
function inverseProject(nx, ny) {
  const x = (nx - 0.5) * 2.0;
  const y = -(ny - 0.5) * 2.0;
  const rho = Math.hypot(x, y);
  if (rho > 1.0) return null;

  const lat0 = (window.appMoonState.librationLat || 0) * Math.PI / 180;
  const lon0 = (window.appMoonState.librationLon || 0) * Math.PI / 180;
  const c = Math.asin(rho);

  const lat = Math.asin(Math.cos(c) * Math.sin(lat0) + (y * Math.sin(c) * Math.cos(lat0)) / rho);
  const lon = lon0 + Math.atan2(x * Math.sin(c), rho * Math.cos(c) * Math.cos(lat0) - y * Math.sin(c) * Math.sin(lat0));

  return { lat: lat * 180 / Math.PI, lon: lon * 180 / Math.PI };
}

function countPoints(features) {
  let total = 0;
  for (const f of features) {
    const coords = f.projectedCoords || f.coords;
    for (const ring of coords) {
      total += ring.length;
    }
  }
  return total;
}

export const GeoJSON = {
  parse,
  parseObject,
  project,
  inverseProject,
  projectPoint,
  countPoints
};
